# Generated by Django 5.1.1 on 2024-12-18 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(9),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "personId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ApartmentBrokerage.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(20000000),
                        ]
                    ),
                ),
                (
                    "rooms",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ApartmentBrokerage.person",
                    ),
                ),
            ],
        ),
    ]
