# Generated by Django 5.1.1 on 2024-12-25 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ApartmentBrokerage",
            "0002_remove_person_email_alter_apartment_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="broker",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="floor",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-10),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="neighborhood",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(20000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="street",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                max_length=10, validators=[django.core.validators.MinLengthValidator(9)]
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
