# Generated by Django 5.1.1 on 2024-12-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ApartmentBrokerage",
            "0003_alter_apartment_broker_alter_apartment_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentBrokerage.person",
            ),
        ),
    ]
