# Generated by Django 4.2.16 on 2025-01-23 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0004_alter_apartment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='personId',
            new_name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
