# Generated by Django 4.2.16 on 2025-01-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0005_rename_personid_broker_person_person_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
