# Generated by Django 4.2.16 on 2025-01-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0007_remove_broker_person_users_message_broker_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentBrokerage.broker'),
        ),
    ]
