# Generated by Django 4.2.16 on 2025-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ApartmentBrokerage', '0011_alter_users_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='person_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='person_set', to='auth.permission'),
        ),
    ]
