# Generated by Django 4.2.16 on 2025-01-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0012_alter_users_groups_alter_users_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentBrokerage.users'),
        ),
    ]
