# Generated by Django 4.2.16 on 2025-01-26 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0013_alter_apartment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='broker',
        ),
        migrations.AddField(
            model_name='apartment',
            name='commission',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
