# Generated by Django 4.2.16 on 2025-01-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0014_remove_apartment_broker_apartment_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='isBrokerage',
            field=models.BooleanField(default=False),
        ),
    ]
