# Generated by Django 4.2.16 on 2025-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0015_apartment_isbrokerage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
