# Generated by Django 4.2.16 on 2025-01-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0016_alter_apartment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
