# Generated by Django 4.2.16 on 2025-01-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentBrokerage', '0017_alter_apartment_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentBrokerage.apartment')),
            ],
        ),
    ]
